create table Teacher(
  id                                int                 not null      AUTO_INCREMENT   	primary key   		comment '主键Id',
  name                              text(20)            not null                                					comment '姓名',   
  age                               tinyint(100)        not null      default '0'                         comment '年龄',
  positional_titles                 char(20)            null          default ''                          comment '职称',
  person_id                         char(20)            not null      default ''                          comment '身份证号码',
  graduate_school                   char(20)            not null      default ''                          comment '毕业院校',
  speciality                        char(20)            not null      default ''                          comment '专业',
  studies_time                      date                null                                              comment '进修时间',
  work_start_time                   date                not null      default '1000-10-10 10:10:10'       comment '工作时间',
  sex                               char(1)             not null      default '男'                        comment '性别',
  graduation_time                   date                not null      default '1000-10-10 10:10:10'       comment '毕业时间',
  obtain_positional_titles_time     date                null                                              comment '获取职称时间',
  administrative_position           char(20)            null          default ''                          comment '行政职务',
  address                           char(50)            not null      default ''                          comment '联系地址',
  phone                             tinyint(11)         not null                               						comment '联系电话',
  sos_person                        char(10)            null          default ''                          comment '紧急联络人',
  sos_person_phone                  tinyint(11)         null          						                        comment '紧急联络人电话',
  is_class_teacher                  boolean      				not null      default false                       comment '是否班主任',
  teach_subject                     char(10)            not null      default ''                          comment '所任学科',
  is_party_member                   boolean      				not null      default false                       comment '是否党员',
  remark                            text                null          							                      comment '备注',
  is_removed                        boolean      				not null      default false                       comment '删除标记'       
) comment = '学生表';