create table Teacher(
  id                                int                 not null      comment '主键Id',
  name                              varchar(10)         not null      comment '姓名',   
  age                               tinyint(100)        not null      comment '年龄',
  positional_titles                 char(10)            null          comment '职称',
  person_id                         char(18)            not null      comment '身份证号码',
  graduate_school                   char(50)            not null      comment '毕业院校',
  speciality                        char(50)            not null      comment '专业',
  studies_time                      date                null          comment '进修时间',
  work_start_time                   date                not null      comment '工作时间',
  sex                               char(1)             not null      comment '性别',
  graduation_time                   date                not null      comment '毕业时间',
  obtain_positional_titles_time     date                null          comment '获取职称时间',
  administrative_position           char(10)            null          comment '行政职务',
  address                           char(100)           not null      comment '联系地址',
  phone                             char(11)            not null      comment '联系电话',
  sos_person                        char(10)            null          comment '紧急联络人',
  sos_person_phone                  char(11)            null          comment '紧急联络人电话',
  is_class_teacher                  boolean(false)      not null      comment '是否班主任',
  teach_subject                     char(10)            not null      comment '所任学科',
  is_party_member                   boolean(false)      not null      comment '是否党员',
  remark                            varchar(65535)      null          comment '备注',
  is_removed                        boolean(false)      not null      comment '删除标记'       
  primary key (id)
) comment = '学生表';